### PR TITLE
Add inputProps prop that can define additional props passed to the InputComponent or override existing ones

### PR DESCRIPTION
**Pull request by synbot**
Also add onBlur and onFocus props.

### CODE REVIEW

**Comment by zpchavez** [comment]
:m: :star:

**Comment by zpchavez** [comment]
Doing more things :o:

**Comment by zpchavez** [comment]
:star:

**Comment by spruce-bruce** [comment]
:pray: We'll test on a project

**Comment by dmmcinty** [comment]
:+1:

**Pull request merged**
